backend:
  name: [ github | gitlab ]
  repo: https://github.com/officialrajdeepsingh/contentLayerNetlifycmsVercel 
  repository branch: main 
  base_url: https://vercel-serverless-functions-for-netlifycms.vercel.app/
  branch: main 
media_folder: "public/images" 
public_folder: "/images" 
collections:
  - name: "blog"
    label: "Blog" 
    folder: "posts"
    create: true 
    slug: "{{title}}" 
    fields: 
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Draft post", name: "draft", widget: "boolean", hint: "Publish post to set to false", required: true, default: true}
